# **************************************************************************
# *
# * Authors:     Alberto García Mena (alberto.garcia@cnb.csic.es)
# *              Scipion Team
# *
# * National Center of Biotechnology, CSIC, Spain
# *
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import logging
import time
import traceback
from collections import Counter
from glob import glob
from os.path import join, getmtime, basename, exists
from statistics import mean
from typing import Union, List, Tuple, Optional
from pwem.emlib.image.image_readers import ImageStack, ImageReadersRegistry
from pwem.objects import SetOfMicrographs
from pwem.protocols import EMProtocol
from pyworkflow import BETA
from pyworkflow.object import Pointer, Set
from pyworkflow.protocol import ProtStreamingBase, BooleanParam, LEVEL_ADVANCED, StringParam, \
    PathParam, PointerParam, IntParam, GE, LE
from pyworkflow.utils import cyanStr, yellowStr, removeBaseExt, redStr
from pyworkflow.utils.retry_streaming import retry_on_sqlite_lock
from tomo.convert.mdoc import MDoc, TiltMetadata
from tomo.objects import SetOfTiltSeries, TiltSeries, TiltImage, TomoAcquisition
from pwem.objects.data import Micrograph


logger = logging.getLogger(__name__)
OUT_TS_SET = "tiltSeries"
MC_EVEN_ODD_ATTRIBUTE = '_mcEvenOddMics'


class ProtComposeTS(EMProtocol, ProtStreamingBase):
    """ Compose in streaming a set of tilt series based on a set of micrographs and mdoc files.
    A time parameter is available for the streaming behaviour: Time to next tilt
    """
    _devStatus = BETA
    _label = 'Compose Tilt Series'
    _possibleOutputs = {OUT_TS_SET: SetOfTiltSeries}

    def __init__(self, **args):
        super().__init__(**args)
        self.time4NextTS_current = time.time()
        self.processedMdocs = []
        self.processedIds = []
        self.listOfMics = None
        self.inMicsAcq = None
        self.sRate = None
        self.numberOfThreads.set(3)

    @classmethod
    def worksInStreaming(cls):
        return True

    # -------------------------- DEFINES AND STEPS -----------------------
    def _defineParams(self, form):
        form.addSection(label='Import')

        form.addParam('inputMicrographs', PointerParam,
                      pointerClass='SetOfMicrographs',
                      important=True,
                      label="Input micrographs",
                      help='Select the SetOfMicrographs to import.')

        form.addParam('filesPath', PathParam,
                      label="Path with the *.mdoc files for each tilt series",
                      help="Root directory of the tilt-series. "
                           "Use of * will work for multiple characters or ? for a single one. "
                           "Also [ ] can specify ranges.")

        form.addParam('mdocPattern', PathParam,
                      label="Mdoc pattern",
                      default="*.mdoc",
                      help="Pattern that should match for mdoc files."
                           "Use of * will work for multiple characters or ? for a single one. "
                           "Also [ ] can specify ranges.")

        form.addParam('excludedWords', StringParam,
                      label="Exclusion words",
                      default="",
                      help="Space separated words that will be used to exclude mdoc files that "
                           "could be listed with the above parameters.")

        form.addParam('isTomo5', BooleanParam,
                      default=False,
                      label="Rotate the tilt axis?",
                      help="If these mdocs were generated by Tomography 5  or other "
                           "software packages that have a different definition of the tilt "
                           "axis angle, check this box to ensure it is converted "
                           "properly: -1 * TiltAxisAngle - 90.")

        form.addParam('doEvenOdd', BooleanParam,
                      default=False,
                      label='Compose the odd/even tilt-series?')

        form.addParam('minNumTilts', IntParam,
                      default=3,
                      label='Min number of tilts allowed in a mdoc file',
                      help='If the number of tilts is lower than the value provided, the corresponding '
                           'mdoc file will be skipped.')

        # form.addParam('mdoc_bug_Correction', BooleanParam,
        #               default=False,
        #               label="mdoc bug Correction",
        #               expertLevel=LEVEL_ADVANCED,
        #               help="Setting True, the mdoc generated by SerialEM "
        #                    "will be read considering the bug: filepath formatting "
        #                    "and ensures tiltA is rounded and consistent.")

        form.addParam('percentTiltsRequired', IntParam,
                      default=50,
                      label="Percent of tilts required (%)",
                      expertLevel=LEVEL_ADVANCED,
                      validators=[GE(50), LE(100)],
                      help="Percentage of tilts in a TiltSeries required to compose the TiltSeries. "
                           "With this parameter, it is possible to generate a TiltSeries without certain tilts, "
                           "caused by a faulty movie or a failure in alignment.")

        form.addSection('Streaming')
        form.addParam('time4NextTilt', StringParam,
                      default="3m",
                      label="Time for the next tilt",
                      help="When the protocol runs in streaming; this parameter determine the delay "
                           "until the next tilt is "
                           "registered in the mdoc file. After "
                           "timeout, the mdoc file is not updated, the tilt series "
                           "is considered as processed. "
                           "The minimum time recommended is 20 secs (20s). "
                           "For PACEtomo acquisiton, please "
                           "increase this time according to your acquisition. "
                           "A correct format is an integer number in "
                           "seconds or the following syntax: {days}d {hours}h "
                           "{minutes}m {seconds}s separated by spaces "
                           "e.g: 1d 2h 20m 15s,  10m 3s, 1h, 20s or 25")

    # -------------------------- STEPS functions ------------------------------
    def stepsGeneratorStep(self):
        closeSetStepDeps = []
        inputSet = self.getInMics()
        self.sRate = inputSet.getSamplingRate()
        self.inMicsAcq = inputSet.getAcquisition()

        while True:
            mdocList = self.findMdocs()
            if not inputSet.isStreamOpen() and Counter(self.processedMdocs) == Counter(mdocList):
                logger.info(cyanStr('Input set closed.'))
                self._insertFunctionStep(self.closeOutputSetsStep,
                                         prerequisites=closeSetStepDeps,
                                         needsGPU=False)
                break

            self.listOfMics = [mic.clone() for mic in inputSet if mic.getObjId() not in self.processedIds]
            nonProcessedMdocs = [mdoc for mdoc in mdocList if mdoc not in self.processedMdocs]
            if nonProcessedMdocs:
                logger.info(cyanStr(f'List of mdocs available to compose: {nonProcessedMdocs}'))
            for mdocFn in nonProcessedMdocs:
                if self.isMdocBanned(mdocFn):
                    self.processedMdocs.append(mdocFn)
                    continue
                # Check the time from the last mdoc file update to consider it closed
                time4NextTilt = self.time4NextTilt.toSeconds()
                if time.time() - getmtime(mdocFn) < time4NextTilt:
                    logger.info(cyanStr(f'Waiting for the next tilt of {mdocFn}'))
                    continue
                # Read the mdoc contents
                errorMsg, mdoc = self.readMdocContents(mdocFn)
                if errorMsg:
                    logger.info(yellowStr(errorMsg))
                    self.processedMdocs.append(mdocFn)
                    continue
                # Match the stack files from the motion-corrected mics and from the mdoc
                matchOk, tiltMdSorted, micsSorted = self.matchTs(mdoc)
                if not matchOk:
                    continue
                cTsPid = self._insertFunctionStep(self.composeTsStep,
                                                  mdoc,
                                                  tiltMdSorted,
                                                  micsSorted,
                                                  prerequisites=[],
                                                  needsGPU=False)
                closeSetStepDeps.append(cTsPid)
                logger.info(cyanStr(f"Steps created for mdoc file = {mdocFn}"))
                self.processedMdocs.append(mdocFn)

            time.sleep(10)
            if inputSet.isStreamOpen():
                with self._lock:
                    inputSet.loadAllProperties()  # refresh status for the streaming

    @retry_on_sqlite_lock(log=logger)
    def composeTsStep(self,
                      mdoc: MDoc,
                      tiltMd: Tuple[TiltMetadata],
                      mics: Tuple[Micrograph]):
        try:
            self.generateOutTs(mdoc, tiltMd, mics)
        except Exception as e:
            logger.error(redStr(f'tsId = {mdoc.getTsId()} - the output generation '
                                f'failed with the exception {e}. '
                                f'Skipping...'))
            logger.error(traceback.format_exc())

    def closeOutputSetsStep(self):
        self._closeOutputSet()
        outTsSet = getattr(self, OUT_TS_SET, None)
        if not outTsSet or (outTsSet and len(outTsSet) == 0):
            raise Exception(f'No output {OUT_TS_SET} were generated. Please check the '
                            f'Output Log > run.stdout and run.stderr')
        # The set is generated and the tilt-series are added, but they are empty (error
        # during the data registering process
        if outTsSet and len(outTsSet) > 0:
            if all([len(ts) == 0 for ts in outTsSet]):
                raise Exception(f'Output {OUT_TS_SET} is empty. This may happen if there '
                                f'was an error during the data registering. Please check the '
                                f'Output Log > run.stdout and run.stderr')


    # --------------------------- UTILS functions -----------------------------
    def getInMics(self, asPointer: bool = False) -> Union[Pointer, SetOfMicrographs]:
        return self.inputMicrographs if asPointer else self.inputMicrographs.get()

    def findMdocs(self) -> List[str]:
        """
        :return: return a sorted by date list of all mdoc files in the path
        """
        fpath = self.filesPath.get()
        mdocList = glob(join(fpath, self.mdocPattern.get()))
        if mdocList:
            mdocList.sort(key=getmtime)
        else:
            logger.info(cyanStr(f'No .mdoc files found in path = {fpath}'))
        return mdocList

    def isMdocBanned(self, mdocFn: str) -> bool:
        for bannedWord in self.excludedWords.getListFromValues(caster=str):
            if bannedWord in mdocFn:
                logger.info(yellowStr(f"mdoc {mdocFn} contains the exclusion "
                                      f"word {bannedWord}. Skipping..."))
                return True
        return False

    def readMdocContents(self, mdocFn: str) -> Tuple[str, Optional[MDoc]]:
        logger.info(cyanStr(f'Reading mdoc file: {mdocFn}...'))
        mdoc = MDoc(mdocFn)
        try:
            mdoc.read(ignoreFilesValidation=True)
            if not mdoc.getTiltAxisAngle():
                errorMsg = f'Unable to read the tilt axis angle from the mdoc file {mdocFn}.'
                return errorMsg, None
        except Exception as e:
            errorMsg = f'Mdoc file {mdocFn} did not pass the format validation with exception {e}'
            return errorMsg, None

        tiltsMdList = mdoc.getTiltsMetadata()
        nImgs = len(tiltsMdList)
        minNumTilts = self.minNumTilts.get()
        if nImgs < minNumTilts:
            errorMsg = (f'Mdoc error -> Mdoc file {mdocFn} contains less [{nImgs}] '
                        f'than minimum allowed [{minNumTilts}].')
            return errorMsg, None
        return '', mdoc

    # @staticmethod
    # def fixingMdocBug(filepath: str, tiltA: float) -> Tuple[str, float]:
    #     idx = filepath.find(']_')
    #     filepath = filepath[:idx + 2] + filepath[idx + 2].upper() + filepath[idx + 3:]
    #     if float(tiltA) - round(float(tiltA), 0) != 0:
    #         filepath = filepath.replace(str(tiltA), str(round(float(tiltA))) + '.00')
    #         tiltA = str(round(float(tiltA))) + '.00'
    #     return filepath, tiltA

    def matchTs(self, mdoc: MDoc)\
            -> Tuple[bool, Optional[Tuple[TiltMetadata]], Optional[Tuple[Micrograph]]]:
        mdocFn = mdoc.getFileName()
        tiltsMdList = mdoc.getTiltsMetadata()
        nTilts = len(tiltsMdList)
        # logger.info(cyanStr(f'Matching {mdocFn}...'))
        # logger.info(cyanStr(f'Tilts on the mdoc file: {nTilts}'))
        # logger.info(cyanStr(f'Micrographs available: {len(self.listOfMics)}'))

        micsBNamesDict = {removeBaseExt(mic.getMicName()): mic for mic in self.listOfMics}
        tiltsMdListFiltered = []
        micsFilteredList = []
        for tiltMd in tiltsMdList:
            micNameFromMdoc = removeBaseExt(tiltMd.getAngleMovieFile())
            if micNameFromMdoc in micsBNamesDict.keys():
                tiltsMdListFiltered.append(tiltMd)
                micsFilteredList.append(micsBNamesDict[micNameFromMdoc])

        nMicsMatched = len(tiltsMdListFiltered)
        if nMicsMatched < nTilts:
            logger.info(cyanStr(f"{mdocFn} -> {nTilts - nMicsMatched} micrographs are not yet available "
                                f"to compose the TiltSeries. Waiting for the tilts to compose..."))
            logger.info(cyanStr(f'Tilts on the mdoc file: {nTilts}'))
            logger.info(cyanStr(f'Motion-corrected tilts found: {nMicsMatched}'))
            return False, None, None
        else:
            percentTiltsAvailable = int(100 * nMicsMatched / nTilts)
            percentTiltsReq = self.percentTiltsRequired.get()
            logger.info(cyanStr(f'Percent tilts available: {percentTiltsAvailable}'))
            logger.info(cyanStr(f'Percent tilts required: {percentTiltsReq}'))
            if percentTiltsAvailable < percentTiltsReq:
                logger.info(yellowStr(
                    f'The mdoc file {mdocFn} will not provide a TiltSeries because'
                    f' {nTilts - nMicsMatched} micrographs ({percentTiltsAvailable}%) are '
                    f'not available to compose the TiltSeries. Modify the parameter '
                    f'"Percent of tilts required" parameter (advanced) if you want this '
                    f'TiltSeries to be generated.'))
                self.processedMdocs.append(mdocFn)
                return False, None, None

        logger.info(cyanStr(f'Micrographs matched for the mdoc file: {nMicsMatched}'))
        # Ensure the tilt metadata list is sorted by angle
        zippedLists = list(zip(tiltsMdListFiltered, micsFilteredList))
        zippedLists.sort(key=lambda x: float(x[0].getTiltAngle()), reverse=False)
        tiltsMdSorted, micsSorted = zip(*zippedLists)
        return True, tiltsMdSorted, micsSorted

    def generateOutTs(self,
                      mdoc: MDoc,
                      tiltsMd: Tuple[TiltMetadata],
                      mics: Tuple[Micrograph]):
        tsId = mdoc.getTsId()
        # MOUNT THE STACKS -----------------------------------------------------------------
        logger.info(cyanStr(f'{tsId} - mounting the stack/s...'))
        tsFn = self._getOutTsFName(tsId)
        properties = {"sr": self.sRate}
        tsStack = ImageStack(properties=properties)
        doEvenOdd = self.doEvenOdd.get()
        oddEvenMics = getattr(mics[0], MC_EVEN_ODD_ATTRIBUTE, None)
        tsStackEven = []
        tsStackOdd = []
        tsFnEven = ''
        tsFnOdd = ''
        if doEvenOdd:
            tsFnEven = self._getOutTsFName(tsId, suffix='_even')
            tsFnOdd = self._getOutTsFName(tsId, suffix='_odd')
            tsStackEven = ImageStack(properties=properties)
            tsStackOdd = ImageStack(properties=properties)

        for mic in mics:
            # Add immage to the stack
            tsStack.append(ImageReadersRegistry.open(mic.getFileName()))
            if doEvenOdd:
                # Odd / even
                tsStackOdd.append(ImageReadersRegistry.open(oddEvenMics[0]))
                tsStackEven.append(ImageReadersRegistry.open(oddEvenMics[1]))

        ImageReadersRegistry.write(tsStack, tsFn, isStack=True)
        if oddEvenMics:
            ImageReadersRegistry.write(tsStackOdd, tsFnOdd, isStack=True)
            ImageReadersRegistry.write(tsStackEven, tsFnEven, isStack=True)

        # COMPOSE THE TILT-SERIES ---------------------------------------------------------
        logger.info(cyanStr(f'{tsId} - composing the tilt series...'))
        with self._lock:
            acq = self._genTomoAcquisition(mdoc, tiltsMd)
            tsSet = self._getOutputTsSet()
            ts = TiltSeries(tsId=tsId)
            tsSet.setAcquisition(acq)
            tsSet.append(ts)

            index = 1
            minAngle = 999
            maxAngle = -999
            initialDose = 999
            accumDose = -999
            for tiltMd, mic in zip(tiltsMd, mics):
                ti = TiltImage()
                acqOrder = int(tiltMd.getAcqOrder())
                tiltAngle = float(tiltMd.getTiltAngle())
                ti.setTsId(tsId)
                ti.setTiltAngle(tiltAngle)
                ti.setIndex(index)
                ti.setFileName(tsFn)
                ti.setSamplingRate(self.sRate)
                ti.setAcquisitionOrder(acqOrder)
                ti.setOddEven([tsFnOdd, tsFnEven] if doEvenOdd else [])
                # Acquisition
                micAcq = mic.getAcquisition()
                tiAcq = acq.clone()
                # Initial and accumulated doses may be zero if the mdoc does not contain the data
                # needed to calculate it.
                inDose = max(tiltMd.getIncomingDose(), micAcq.getDosePerFrame() * (acqOrder - 1))
                cumDose = max(tiltMd.getAccumDose(), micAcq.getDosePerFrame() * acqOrder)
                tiAcq.setDoseInitial(inDose)
                tiAcq.setAccumDose(cumDose)
                ti.setAcquisition(tiAcq)
                ts.append(ti)
                self.processedIds.append(mic.getObjId())
                index += 1
                # Update the values needed for the acquisition of the tilt-series
                minAngle = min(tiltAngle, minAngle)
                maxAngle = max(tiltAngle, maxAngle)
                initialDose = min(inDose, initialDose)
                accumDose = max(cumDose, accumDose)

            tsAcq = ts.getAcquisition()
            tsAcq.setDoseInitial(initialDose)
            tsAcq.setAccumDose(accumDose)
            tsAcq.setAngleMin(minAngle)
            tsAcq.setAngleMax(maxAngle)
            tsAcq.setTiltAxisAngle(mdoc.getTiltAxisAngle())
            ts.setAcquisition(tsAcq)
            # Data persistence
            ts.write()
            tsSet.update(ts)
            tsSet.write()
            self._store(tsSet)
            for outputName in self._possibleOutputs.keys():
                output = getattr(self, outputName, None)
                if output:
                    output.close()

    def _genTomoAcquisition(self,
                            mdoc: MDoc,
                            tiltsMdList: Tuple[TiltMetadata]) -> TomoAcquisition:
        nImgs = len(tiltsMdList)
        inMicsVoltage = self.inMicsAcq.getVoltage()
        inMicsMagnification = self.inMicsAcq.getMagnification()
        voltage = inMicsVoltage if inMicsVoltage else mdoc.getVoltage()
        magnification = inMicsMagnification if inMicsMagnification else mdoc.getMagnification()
        acq = TomoAcquisition()
        acq.setVoltage(voltage)
        acq.setMagnification(magnification)
        acq.setSphericalAberration(self.inMicsAcq.getSphericalAberration())
        acq.setAmplitudeContrast(self.inMicsAcq.getAmplitudeContrast())
        acq.setDosePerFrame(self.inMicsAcq.getDosePerFrame())
        acq.setAngleMin(float(tiltsMdList[0].getTiltAngle()))
        acq.setAngleMax(float(tiltsMdList[-1].getTiltAngle()))
        step = round(mean([float(tiltsMdList[i + 1].getTiltAngle()) -
                           float(tiltsMdList[i].getTiltAngle()) for i in
                           range(nImgs - 1)]))
        acq.setStep(step)
        acq.setAccumDose(float(tiltsMdList[-1].getAccumDose()))
        tiltAxisAngle = mdoc.getTiltAxisAngle()
        tiltAxisAngle = -1 * tiltAxisAngle - 90 if self.isTomo5.get() else tiltAxisAngle
        acq.setTiltAxisAngle(tiltAxisAngle)
        return acq

    def _getOutputTsSet(self) -> SetOfTiltSeries:
        tsSet = getattr(self, OUT_TS_SET, None)
        if tsSet:
            tsSet.enableAppend()
        else:
            tsSet = SetOfTiltSeries.create(self._getPath(), template='tiltseries', suffix='_composed')
            tsSet.setSamplingRate(self.sRate)
            tsSet.setStreamState(Set.STREAM_OPEN)
            self._defineOutputs(**{OUT_TS_SET: tsSet})
            self._defineSourceRelation(self.inputMicrographs, tsSet)
        return tsSet

    def _getOutTsFName(self, tsId: str, suffix: str = '') -> str:
        return self._getExtraPath(f'{tsId}{suffix}.mrcs')

    def _validate(self):
        errorMsgs = []
        oddEvenMics = getattr(self.getInMics()[1], MC_EVEN_ODD_ATTRIBUTE, None)
        if self.doEvenOdd.get() and not oddEvenMics:
            errorMsgs.append('Odd/Even tilt-series were requested to be composed, '
                             'but the motion-corrected micrographs introduced do '
                             'not have the in their metadata.')
        return errorMsgs

    def _summary(self):
        summary = [f'Path with the *.mdoc files for each tilt series:{self.filesPath.get()}\n']
        summaryF = self._getExtraPath("summary.txt")
        if not exists(summaryF):
            summary.append("No summary file yet.")
        else:
            summaryF = open(summaryF, "r")
            for line in summaryF.readlines():
                summary.append(line.rstrip())
            summaryF.close()
        return summary
