# coding=utf-8
# **************************************************************************
# *
# * Authors:     Federico P. de Isidro Gomez (fp.deisidro@cnb.csi.es) [1]
# *
# * [1] Centro Nacional de Biotecnologia, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import pyworkflow.protocol.params as params
from pyworkflow.object import Set

from ..objects import SetOfTiltSeriesCoordinates, TiltSeriesCoordinate
from .protocol_base import ProtTomoImportFiles
from ..utils import existsPlugin

IMPORT_FROM_TXT = 'txt'
IMPORT_FROM_IMOD = 'imod'
OUTPUT_TS_COORDINATES_NAME = "TiltSeriesCoordinates"


class ProtImportTiltSeriesCoordinates(ProtTomoImportFiles):
    """
    Imports a set of 3D coordinates associated with tilt-series.

    AI Generated:

    Import Tilt-Series Coordinates (ProtImportTiltSeriesCoordinates) — User Manual
        Overview

        The Import Tilt-Series Coordinates protocol imports 3D coordinates associated
        with a set of tilt-series.

        This protocol is commonly used in cryo-electron tomography workflows when
        coordinates have been generated outside Scipion, for example through manual
        picking, fiducial annotation, or external preprocessing software.

        Each imported coordinate is linked to its corresponding tilt-series through
        the tilt-series identifier (tsId), allowing the imported data to remain
        consistent with the tomography dataset.

        The protocol supports importing coordinates from plain text files and,
        when available, from IMOD-generated files.

        Inputs and General Workflow

        The protocol requires:

        - A set of tilt-series
        - A collection of coordinate files

        Each coordinate file must correspond to one tilt-series. Matching is based
        on the presence of the tilt-series identifier (tsId) inside the coordinate
        filename.

        During execution, the protocol iterates through every tilt-series in the
        input set and searches for the coordinate file whose filename contains
        the corresponding tsId.

        Once the match is found, coordinates are read, converted into
        TiltSeriesCoordinate objects, and appended to the output set.

        Supported Import Modes

        The protocol currently supports two import modes.

        TXT Import

        In TXT mode, coordinates are read from plain text files.

        Each non-empty line is parsed and interpreted as a 3D coordinate.
        The protocol assumes that coordinates follow a format in which the
        origin corresponds to the top-left corner of the reference tilt-image.

        Coordinates are imported directly without applying any geometric
        recentering correction.

        IMOD Import

        When the IMOD plugin is installed, the protocol can also import
        coordinates generated by IMOD.

        In this mode, the protocol uses IMOD utilities to read the
        coordinate list and the dimensions of the reference image.

        The X and Y coordinates are recentered so that the origin is placed
        at the geometric center of the tilt-image.

        This is particularly important because IMOD coordinates are usually
        expressed relative to the image corner rather than the center.

        Coordinate Construction

        For each imported point, the protocol creates a new
        TiltSeriesCoordinate object.

        Each coordinate stores:

        - The tilt-series identifier (tsId)
        - X, Y, and Z spatial coordinates
        - The sampling rate inherited from the corresponding tilt-series

        This ensures that the coordinates remain physically meaningful and
        compatible with downstream tomographic processing.

        Output Generation

        The protocol generates a SetOfTiltSeriesCoordinates output object.

        The output set keeps an explicit reference to the input set of
        tilt-series, preserving the relationship between imported coordinates
        and their corresponding acquisition geometry.

        Coordinates are appended progressively during import, and once all
        tilt-series have been processed, the output stream is closed.

        Validation and Error Handling

        Before execution, the protocol validates that every tilt-series has
        a matching coordinate file.

        If a tilt-series does not have a corresponding file, a validation
        warning is generated.

        This validation is particularly important because the protocol
        relies entirely on filename-based matching.

        When IMOD import is selected, the protocol also checks whether
        the IMOD plugin is installed.

        If the plugin is missing, the user receives an explicit validation
        message.

        Practical Recommendations

        For reliable results, coordinate filenames should contain the
        exact tilt-series identifier.

        Consistent naming conventions are critical, especially when working
        with large tomographic datasets.

        When importing from IMOD, users should remember that coordinates
        are automatically recentered.

        When importing from TXT files, coordinates are assumed to already
        be expressed in the desired coordinate system.

        Biological Interpretation

        This protocol does not modify images or perform reconstruction.

        Its purpose is to integrate externally generated spatial annotations
        into the Scipion tomography workflow.

        In biological practice, these coordinates often represent:

        - Fiducial marker positions
        - Candidate particle locations
        - Reference landmarks
        - Manually curated points of interest

        Correct coordinate import is therefore essential for downstream
        tasks such as alignment validation, subtomogram extraction,
        particle picking refinement, or structural interpretation.

        Final Perspective

        The Import Tilt-Series Coordinates protocol is a utility protocol
        focused on metadata integration rather than image processing.

        Although computationally simple, it solves an important practical
        problem in cryo-electron tomography workflows: transferring
        externally generated 3D coordinate information into a consistent
        Scipion-compatible representation.
    """
    _outputClassName = 'SetOfCoordinates3D'
    _label = 'import tilt-series coordinates'
    _possibleOutputs = {OUTPUT_TS_COORDINATES_NAME: SetOfTiltSeriesCoordinates}

    def _getImportChoices(self):
        """ Return a list of possible choices from which the import can be done.
        """
        importChoices = [IMPORT_FROM_TXT]
        if existsPlugin('imod'):
            importChoices.append(IMPORT_FROM_IMOD)
        return importChoices

    def _defineAcquisitionParams(self, form):
        pass

    def __init__(self, **args):
        ProtTomoImportFiles.__init__(self, **args)

        self.TiltSeriesCoordinates = None

    def _defineParams(self, form):
        ProtTomoImportFiles._defineParams(self, form)

        form.addParam('inputSetOfTiltSeries',
                      params.PointerParam,
                      pointerClass='SetOfTiltSeries',
                      important=True,
                      label='Input set of tilt-series')

    def _insertAllSteps(self):
        self.fileList = [file for file, _ in self.iterFiles()]

        if self.getImportFrom() == IMPORT_FROM_IMOD:
            for ts in self.inputSetOfTiltSeries.get():
                self._insertFunctionStep(self.importCoordinatesFromImodStep,
                                         ts.getObjId())

        elif self.getImportFrom() == IMPORT_FROM_TXT:
            for ts in self.inputSetOfTiltSeries.get():
                self._insertFunctionStep(self.importCoordinatesStep,
                                         ts.getObjId())

        self._insertFunctionStep(self.createOutputStep)

    # --------------------------- STEPS functions -----------------------------

    def importCoordinatesFromImodStep(self, tsObjId):
        from imod import utils as imodUtils
        ts = self.inputSetOfTiltSeries.get()[tsObjId]
        tsId = ts.getTsId()

        self.getOutputSetOfTiltSeriesCoordinates(self.inputSetOfTiltSeries.get())

        for coordFilePath in self.fileList:
            if tsId in coordFilePath:
                break

        coordList, xDim, yDim = imodUtils.format3DCoordinatesList(coordFilePath)

        for element in coordList:
            newCoord3D = TiltSeriesCoordinate()
            newCoord3D.setTsId(ts.getTsId())
            newCoord3D.setPosition(element[0] - (xDim / 2),
                                   element[1] - (yDim / 2),
                                   element[2],
                                   sampling_rate=ts.getSamplingRate())

            self.TiltSeriesCoordinates.append(newCoord3D)
        self.TiltSeriesCoordinates.write()
        self._store()

    def importCoordinatesFromTxtStep(self, tsObjId):
        ts = self.inputSetOfTiltSeries.get()[tsObjId]
        tsId = ts.getTsId()

        self.getOutputSetOfTiltSeriesCoordinates(self.inputSetOfTiltSeries.get())

        for coordFilePath in self.fileList:
            if tsId in coordFilePath:
                break

        coordList = self.format3DCoordinatesList(coordFilePath)

        for element in coordList:
            newCoord3D = TiltSeriesCoordinate()
            newCoord3D.setTsId(ts.getTsId())
            newCoord3D.setPosition(element[0],
                                   element[1],
                                   element[2],
                                   sampling_rate=ts.getSamplingRate())

            self.TiltSeriesCoordinates.append(newCoord3D)
        self.TiltSeriesCoordinates.write()
        self._store()

    def createOutputStep(self):
        if self.TiltSeriesCoordinates:
            self.TiltSeriesCoordinates.setStreamState(Set.STREAM_CLOSED)

        self._store()

    # ------------------ UTILS functions --------------------------------------
    def getImportFrom(self):
        importFrom = self._getImportChoices()[self.importFrom.get()]

        return importFrom

    @staticmethod
    def format3DCoordinatesList(coordFilePath):
        """ This method takes a txt fiducial coordinates file path and returns a list containing each coordinate
        information. This assumes that coordinates origin is top left corner, centered at the 0º tilt-image."""

        coorList = []

        with open(coordFilePath) as f:
            coorText = f.read().splitlines()

            for i, line in enumerate(coorText):
                if line != '':
                    vector = line.replace('-', ' -').split()

                    coorList.append([int(vector[1]), int(vector[2]), int(vector[3])])

        return coorList

    def getOutputSetOfTiltSeriesCoordinates(self, setOfTiltSeries=None):

        if self.TiltSeriesCoordinates:
            self.TiltSeriesCoordinates.enableAppend()

        else:
            outputSetOfCoordinates3D = SetOfTiltSeriesCoordinates.create(self._getPath(),
                                                                         suffix='tsCoords')

            outputSetOfCoordinates3D.setSetOfTiltSeries(setOfTiltSeries)
            outputSetOfCoordinates3D.setStreamState(Set.STREAM_OPEN)

            self._defineOutputs(**{OUTPUT_TS_COORDINATES_NAME: outputSetOfCoordinates3D})
            self._defineSourceRelation(setOfTiltSeries, outputSetOfCoordinates3D)

        return self.TiltSeriesCoordinates

    # --------------------------- INFO functions ------------------------------
    def _summary(self):
        summary = []

        return summary

    def _methods(self):
        methods = []

        return methods

    def _validate(self):
        validateMsgs = []

        match = False

        for ts in self.inputSetOfTiltSeries.get():
            tsId = ts.getTsId()

            for coordsFilePath, _ in self.iterFiles():
                if tsId in coordsFilePath:
                    match = True
                    break

            if not match:
                validateMsgs.append("No coordinates file found for tilt-series %s: image file is %s and have not "
                                    "found its exact match." % (tsId, ts.getFileName()))

            match = False

        if self.getImportFrom() == IMPORT_FROM_IMOD and not existsPlugin('imod'):
            validateMsgs.append('Plugin *scipion-em-imod* has not being installed. Please, install the Plugin to '
                                'import IMOD related formats (currently supported formats: ".txt"). Otherwise, the '
                                'protocol may have unexpected outputs if Eman files are attempted to be imported.\n')

        return validateMsgs
