# coding=utf-8
# **************************************************************************
# *
# * Authors:     Scipion Team  (scipion@cnb.csic.es) [1]
# *
# * [1] Centro Nacional de Biotecnología (CSIC), Madrid, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
from os.path import basename

from pyworkflow import BETA
import pyworkflow.utils as pwutils

import pyworkflow.protocol.params as params
from pyworkflow.plugin import Domain
from pyworkflow.protocol import LEVEL_ADVANCED
from pyworkflow.utils import replaceBaseExt, removeBaseExt

from ..objects import SetOfCoordinates3D
from .protocol_base import ProtTomoImportFiles
from ..convert import TomoImport, EmTableCoordImport
from ..utils import existsPlugin

import tomo.constants as const

IMPORT_FROM_AUTO = 'auto'
IMPORT_FROM_TXT = 'txt'
IMPORT_FROM_EMAN = 'eman'
IMPORT_FROM_DYNAMO = 'dynamo'
IMPORT_FROM_CBOX = 'cbox'


class ProtImportCoordinates3D(ProtTomoImportFiles):

    """Protocol to import a set of tomograms to the project"""



    """
    Imports 3D particle coordinates associated with tomograms from
    different tomography software formats. The protocol establishes
    a correspondence between tomograms and coordinate files and
    generates a unified SetOfCoordinates3D object that can be used
    in downstream subtomogram analysis workflows.

    AI Generated:

    Import Coordinates 3D (ProtImportCoordinates3D) — User Manual
        Overview

        The Import Coordinates 3D protocol is designed to incorporate
        previously identified particle coordinates into a Scipion
        tomography project. Its main purpose is to associate spatial
        particle positions with their corresponding tomograms so that
        these coordinates can later be used for subtomogram extraction,
        particle visualization, template matching validation, or
        downstream structural analysis.

        In cryo-electron tomography workflows, coordinates are often
        generated outside Scipion using particle-picking or annotation
        software such as Dynamo, EMAN, crYOLO, or custom manual picking
        tools. This protocol provides a standardized mechanism to import
        those coordinates while preserving their geometric relationship
        with the tomograms.

        From a biological perspective, this protocol represents the bridge
        between tomographic reconstruction and subtomogram analysis.
        Accurate coordinate import is therefore critical because any
        mismatch in scaling, orientation, or tomogram association may
        propagate errors into all subsequent processing steps.

        Inputs and General Workflow

        During execution, the protocol scans the coordinate files, detects
        or uses the selected import format, and parses the coordinates for
        each tomogram independently. The imported coordinates are then
        converted into a unified internal representation compatible with
        Scipion tomography workflows.

        The protocol supports multiple coordinate formats commonly used in
        cryo-electron tomography pipelines. TXT files can be imported as
        generic coordinate lists, EMAN JSON files are supported when the
        emantomo plugin is installed, Dynamo TBL files are available through
        the dynamo plugin, and CBOX files generated by crYOLO can also be
        imported directly.

        Coordinate and Tomogram Sampling Rates

        One of the most biologically important aspects of this protocol is
        the management of sampling rates. Coordinates are meaningful only
        when expressed in the same spatial scale as the tomograms to which
        they belong.

        If the coordinate sampling rate is not provided, the protocol assumes
        that coordinates and tomograms already share the same pixel size.
        This is the safest and most common situation when the coordinates
        were generated directly from the imported tomograms.

        However, in many practical cryo-ET workflows, coordinates may have
        been generated from tomograms that were binned, resized, or processed
        at a different resolution. In these cases, the protocol automatically
        computes a scaling factor between the coordinate sampling rate and
        the tomogram sampling rate. All imported coordinates are then rescaled
        accordingly before being stored.

        Biologically, this step is essential because incorrect scaling may
        lead to particles being extracted from completely wrong positions.
        Even small scaling mismatches can significantly affect subtomogram
        averaging quality and downstream structural interpretation.

        Box Size Interpretation

        The protocol also allows the user to define a box size associated
        with the imported coordinates. This box size represents the expected
        extraction region around each particle and is automatically scaled
        according to the coordinate-to-tomogram sampling ratio.

        In practical terms, the box size should approximately correspond to
        the expected molecular dimensions of the biological complex of interest.
        Choosing a box size that is too small may truncate structural features,
        while excessively large boxes increase computational cost and may
        introduce unnecessary background signal.

        Import Format Detection and Compatibility

        The protocol can automatically detect the coordinate format based on
        file extensions. This simplifies routine workflows where users may
        combine coordinate files generated by different tomography software.

        TXT files are interpreted as generic coordinate lists and are useful
        for simple workflows or manually curated coordinates. EMAN JSON files
        provide compatibility with EMAN-based tomography pipelines, while
        Dynamo TBL files support subtomogram averaging workflows frequently
        used in structural cell biology. CBOX support enables integration with
        modern deep-learning particle pickers such as crYOLO.

        Some formats require external plugins to be installed. If the
        corresponding plugin is missing, the protocol generates warnings to
        inform the user that import functionality may be incomplete or invalid.
        This behavior prevents silent failures and improves workflow reliability.

        Coordinate Association Strategy

        The association between tomograms and coordinates is entirely based on
        filename matching without extensions. This design ensures a simple and
        reproducible correspondence mechanism across datasets.

        From a workflow perspective, maintaining consistent naming conventions
        is extremely important. If coordinate and tomogram filenames do not
        match correctly, the protocol will not be able to establish the
        relationship between them, and the affected files will be ignored or
        reported as mismatches.

        The protocol performs validation checks before execution to ensure
        that at least some tomograms and coordinate files can be associated.
        Additional warnings are generated whenever unmatched tomograms or
        coordinate files are detected.

        Outputs and Their Interpretation

        After execution, the protocol generates a SetOfCoordinates3D object
        containing all successfully imported particle positions linked to
        their corresponding tomograms.

        Each coordinate preserves its spatial position within the tomogram
        reference frame and becomes immediately available for downstream
        tomography protocols such as subtomogram extraction, visualization,
        classification, or averaging.

        The imported coordinates also retain information about the effective
        box size and sampling rate, ensuring consistency throughout the
        subsequent processing pipeline.

        Practical Recommendations

        In routine cryo-ET workflows, it is strongly recommended to verify
        that tomograms and coordinate files follow identical naming conventions
        before import. Most import failures originate from filename mismatches
        rather than coordinate parsing problems.

        Users should also verify that coordinate sampling rates correspond to
        the tomogram resolution used during picking. When coordinates originate
        from binned tomograms, providing the correct coordinate sampling rate
        is essential for accurate particle localization.

        For biological datasets with heterogeneous particle sizes, selecting
        an appropriate box size is important because it directly influences
        later subtomogram extraction quality.

        When importing coordinates generated by external software, visual
        inspection after import is highly recommended. Confirming that particles
        appear correctly centered within tomograms is one of the most reliable
        ways to detect scaling or association problems early in the workflow.

        Final Perspective

        For tomography users, coordinate import is not simply a file conversion
        task but a critical spatial registration step that connects particle
        localization with structural analysis. Proper scaling, accurate tomogram
        association, and careful validation of imported coordinates are essential
        to ensure biologically meaningful subtomogram analysis results.
    """