# coding=utf-8
# **************************************************************************
# *
# * Authors:     Federico P. de Isidro Gomez (fp.deisidro@cnb.csi.es) [1]
# *
# * [1] Centro Nacional de Biotecnologia, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import pyworkflow.protocol.params as params
from pyworkflow.object import Set

from ..objects import SetOfTiltSeriesCoordinates, TiltSeriesCoordinate
from .protocol_base import ProtTomoImportFiles
from ..utils import existsPlugin

IMPORT_FROM_TXT = 'txt'
IMPORT_FROM_IMOD = 'imod'
OUTPUT_TS_COORDINATES_NAME = "TiltSeriesCoordinates"


class ProtImportTiltSeriesCoordinates(ProtTomoImportFiles):
    """Protocol to import a set of tilt-series coordinates 3D"""

    """
    Imports 3D fiducial or particle coordinates associated with a set of
    tilt-series. The protocol supports importing coordinates from plain
    text files or IMOD-compatible coordinate files and converts them into
    a unified Scipion SetOfTiltSeriesCoordinates object for downstream
    tomographic processing.

    AI Generated:

    Import Tilt-Series Coordinates (ProtImportTiltSeriesCoordinates) — User Manual

        Overview

        The Import Tilt-Series Coordinates protocol is designed to load
        3D coordinate information associated with tomographic tilt-series
        datasets into the Scipion framework. These coordinates usually
        correspond to fiducial markers, particles, landmarks, or manually
        identified positions that are later used in tomographic alignment,
        reconstruction, subtomogram extraction, or structural analysis.

        In cryo-electron tomography workflows, coordinate information is
        biologically and computationally important because it defines
        spatial locations inside reconstructed tomograms or tilt-series
        acquisitions. Correct coordinate import ensures that downstream
        procedures operate within the proper geometric reference system.

        The protocol supports both standard text-based coordinate files
        and IMOD-related coordinate formats when the IMOD plugin is
        available in the Scipion installation. This flexibility allows
        integration with external tomography processing pipelines commonly
        used in structural biology laboratories.

        Inputs and General Workflow

        The protocol requires an input SetOfTiltSeries that defines the
        experimental tilt-series associated with the coordinates being
        imported. Each tilt-series is matched against coordinate files
        available in the selected import directory. Matching is performed
        using the tilt-series identifier, meaning that coordinate files
        must contain the corresponding tilt-series ID in their filename.

        During execution, the protocol iterates through all tilt-series
        and searches for the corresponding coordinate file. Once a match
        is found, coordinates are parsed and converted into internal
        TiltSeriesCoordinate objects associated with the corresponding
        tilt-series.

        The imported coordinates are progressively appended into a
        SetOfTiltSeriesCoordinates object that remains open during import
        and is automatically closed once all files have been processed.

        Coordinate Import from TXT Files

        When importing from standard TXT files, the protocol assumes a
        simple coordinate representation where each valid line contains
        X, Y, and Z coordinate values. The parser ignores empty lines and
        converts coordinate values into integer spatial positions.

        The imported coordinates preserve the original coordinate system
        present in the text file. This mode is particularly useful for
        custom coordinate annotations, manually curated datasets, or
        outputs generated by external scripts and non-IMOD software.

        From a practical perspective, users should ensure that coordinate
        files follow a consistent formatting convention and that coordinate
        values correspond to the same sampling rate and spatial reference
        frame as the associated tilt-series.

        Coordinate Import from IMOD

        When the IMOD plugin is installed, the protocol can directly
        import IMOD-compatible coordinate information. In this case,
        coordinates are processed using IMOD utility functions that
        interpret the original file structure and extract both coordinate
        positions and image dimensions.

        Unlike the TXT import mode, IMOD coordinates are internally
        recentered relative to the image dimensions. The protocol shifts
        X and Y coordinates by subtracting half of the image size so that
        coordinates become centered with respect to the tomogram reference
        frame rather than the upper-left image corner.

        This transformation is biologically important because many
        tomographic processing algorithms assume centered coordinate
        systems during alignment, reconstruction, or subtomogram analysis.
        Improper coordinate centering may lead to systematic localization
        errors in downstream analyses.

        Coordinate System and Sampling Considerations

        Each imported coordinate is associated with the sampling rate of
        the corresponding tilt-series. Maintaining this relationship is
        essential because coordinate interpretation depends directly on
        voxel size and acquisition scaling.

        The protocol assumes that TXT coordinates originate from a
        coordinate system whose origin is located at the upper-left corner
        of the zero-degree tilt image. Users should therefore verify that
        external coordinate generation tools use compatible conventions.

        In biological tomography workflows, coordinate consistency is
        critical when combining data from multiple software environments.
        Even small coordinate mismatches may affect particle picking,
        subtomogram extraction accuracy, or fiducial alignment precision.

        Output Generation

        The main output of the protocol is a
        SetOfTiltSeriesCoordinates object containing all imported
        coordinates linked to their corresponding tilt-series.

        During execution, the output set operates in streaming mode,
        allowing coordinates to be progressively appended as files are
        processed. Once import is completed, the protocol closes the
        output stream to indicate that no further coordinates will be
        added.

        The resulting coordinate set can then be used by downstream
        tomography protocols inside Scipion, including subtomogram
        extraction, alignment refinement, particle localization, or
        tomogram annotation workflows.

        Validation and Error Detection

        Before execution, the protocol validates that every tilt-series
        has a corresponding coordinate file available in the import
        directory. If no matching file is found for a given tilt-series,
        the protocol reports a validation error indicating the missing
        correspondence.

        Additional validation is performed for IMOD imports. If the user
        selects IMOD mode without having the scipion-em-imod plugin
        installed, the protocol generates a warning indicating that IMOD
        support is unavailable.

        These validation steps are important because coordinate import
        errors are often difficult to detect visually and may propagate
        unnoticed into later stages of tomographic analysis.

        Practical Recommendations

        In routine tomography workflows, users should carefully verify
        filename conventions before execution to ensure that each
        tilt-series correctly matches its coordinate file. Maintaining
        consistent naming schemes across acquisition and annotation
        pipelines significantly reduces import errors.

        For IMOD-generated datasets, using the IMOD import mode is
        generally preferable because it preserves compatibility with
        established tomography processing standards and automatically
        handles coordinate centering.

        For custom workflows or manually curated coordinates, TXT import
        mode provides greater flexibility and simpler interoperability
        with external tools or scripting environments.

        After import, it is advisable to visually inspect a subset of
        coordinates within tomograms or tilt-series viewers to confirm
        that coordinate orientation, centering, and scaling are correct.

        Final Perspective

        Importing tilt-series coordinates is not simply a data conversion
        task but a critical geometric standardization step in cryo-electron
        tomography workflows. Reliable coordinate management ensures that
        downstream structural interpretation, subtomogram localization,
        and biological analysis remain spatially consistent throughout
        the processing pipeline.

        Careful validation of coordinate conventions, file matching, and
        sampling consistency is essential for producing accurate and
        biologically meaningful tomographic results.
    """